config/routes.rb
# This file is a part of Redmine Finance (redmine_finance) plugin,
# simple accounting plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_finance is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_finance is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_finance.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :accounts
resources :operations do
  collection do
      post :bulk_update
      get :bulk_edit, :context_menu, :auto_complete
      delete :bulk_destroy
  end
end
resources :operation_categories
resources :operation_comments, :only => [:create, :destroy]
resources :operation_invoices, :only => [:create, :destroy]
resources :operation_relations, :only => [:create, :destroy]

resources :operation_imports, :only => [:new, :create]

resources :projects do
  resources :operations

  resources :operation_imports, :only => [:new, :create, :show] do
    member do
      get :settings
      post :settings
      get :mapping
      post :mapping
      get :run
      post :run
    end
  end
end

resources :projects do
  resources :accounts
end

app/controllers/operation_invoices_controller.rb
# This file is a part of Redmine Finance (redmine_finance) plugin,
# simple accounting plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_finance is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_finance is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_finance.  If not, see <http://www.gnu.org/licenses/>.

class OperationInvoicesController < ApplicationController
  unloadable

  before_filter :find_operation, :authorize
  before_filter :find_operation_object

  def create
    @operation_object = OperationObject.new(:operationable => @operationable)
    @operation_object.operation = @operation
    saved = @operation_object.save

    respond_to do |format|
      format.html { redirect_to :controller => 'operations', :action => 'show', :id => @operation }
      format.js {
        @invoices = find_operation_invoices
        render :template => "operation_objects/create"
      }
    end
  end

  def destroy
    @operation.invoices.destroy(@operationable)
    @operation_object = OperationObject.new if RedmineFinance.invoices_plugin_installed?
    respond_to do |format|
      format.html { redirect_to :back }
      format.js {
        @invoices = find_operation_invoices
        render :template => "operation_objects/destroy"
      }
    end
  end

private
  def find_operation
    @operation = Operation.find(params[:operation_id])
    @project = @operation.project
  rescue
    render_404
  end

  def find_operation_object
    if object_id = params[:object_id] || (params[:operation_object] && params[:operation_object][:operationable_id])
      @operationable = Invoice.visible.find(object_id)
    end
  rescue
    render_404
  end

  def find_operation_invoices
    @operation.invoices.visible
  end

end

app/views/operation_invoices/_form.html.erb
<%= error_messages_for 'operation_object' %>

<p>
<%= l(:label_invoice) %> #<%= f.text_field :operationable_id, :size => 10 %>
<%= submit_tag l(:button_add) %>
<%= link_to_function l(:button_cancel), '$("#new-operation-invoice-form").hide();'%>
</p>

<%= javascript_tag "observeAutocompleteField('operation_object_operationable_id', '#{escape_javascript auto_complete_invoices_path }')" %>

<%= javascript_tag "setPredecessorFieldsVisibility();" %>

app/views/operation_invoices/_operations.html.erb
<% operations = Operation.visible.eager_load(:operation_objects).where(:operation_objects => {
    :operationable_id => @invoice.id, 
    :operationable_type => @invoice.class.name}) %>

<% if operations.any? %>    

<hr/>
<div id="operations">
  <p><strong><%=l(:label_operation_plural)%></strong></p>
  <% operations.each do |operation| %>
    <p class="icon icon-operation"><%= link_to "#{operation.category.name} ##{operation.id}: #{operation.amount_with_sign} (#{operation.account.name})", operation_path(operation) %>
      <span class="contact"><%= operation.contact.name if operation.contact %></span>
      <%= link_to image_tag('link_break.png'), {:controller => 'operation_invoices', 
                                            :action => 'destroy',
                                            :id => @invoice.id, 
                                            :object_id => @invoice.id,
                                            :operation_id => operation},
                                  :method => :delete,
                                  :data => {:confirm => l(:text_are_you_sure)},
                                  :title => l(:label_relation_delete) if User.current.allowed_to?(:manage_operation_invoices, @project) %>      
    </p>
  <% end %>
</div>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag :finance, :plugin => 'redmine_finance' %> 
<% end %>

<% end %>