config/routes.rb
# This file is a part of Redmine Finance (redmine_finance) plugin,
# simple accounting plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_finance is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_finance is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_finance.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :accounts
resources :operations do
  collection do
      post :bulk_update
      get :bulk_edit, :context_menu, :auto_complete
      delete :bulk_destroy
  end
end
resources :operation_categories
resources :operation_comments, :only => [:create, :destroy]
resources :operation_invoices, :only => [:create, :destroy]
resources :operation_relations, :only => [:create, :destroy]

resources :operation_imports, :only => [:new, :create]

resources :projects do
  resources :operations

  resources :operation_imports, :only => [:new, :create, :show] do
    member do
      get :settings
      post :settings
      get :mapping
      post :mapping
      get :run
      post :run
    end
  end
end

resources :projects do
  resources :accounts
end

app/views/settings/_finance.html.erb
<% finance_tabs = [{:name => 'general', :partial => 'settings/finance_general', :label => :label_general},
        {:name => 'operation_categories', :partial => 'settings/operation_categories', :label => :label_operation_category_plural}
        ]   %>   

<%= render_tabs finance_tabs %>

<% html_title(l(:label_settings), l(:label_finance)) -%>  

app/views/settings/_finance_general.html.erb
<p>
  <label><%= l(:label_finance_show_in_top_menu) %></label>
  <%= hidden_field_tag 'settings[show_in_top_menu]', 0, :id => nil %>
  <%= check_box_tag 'settings[show_in_top_menu]', 1, @settings[:show_in_top_menu].to_i > 0 %>
</p>

<p>
  <label><%= l(:label_finance_show_in_app_menu) %></label>
  <%= hidden_field_tag 'settings[show_in_app_menu]', 0, :id => nil %>
  <%= check_box_tag 'settings[show_in_app_menu]', 1, @settings[:show_in_app_menu].to_i > 0 %>
</p>

<p>
  <label><%= l(:label_finance_filter_companies) %></label>
  <%= check_box_tag 'settings[finance_filter_companies]', 1, @settings[:finance_filter_companies].to_i > 0 %>
</p>
<p>
  <label><%= l(:label_finance_operations_approval) %></label>
  <%= hidden_field_tag 'settings[finance_operations_approval]', 0, :id => nil %>
  <%= check_box_tag 'settings[finance_operations_approval]', 1, @settings[:finance_operations_approval].to_i > 0 %>
</p>

app/views/settings/_operation_categories.html.erb
<div class="contextual">
<%= link_to l(:label_operation_category_new), {:controller => "operation_categories", :action => 'new'}, :class => 'icon icon-add' %>
</div>

<h3><%=l(:label_operation_category_plural)%></h3>
 
<table class="list">
  <thead><tr>
  <th><%=l(:field_operation_category)%></th>
  <th><%=l(:field_operation_category_code)%></th>
  <th></th>
  </tr></thead>
  <tbody>
    <% OperationCategory.category_tree(OperationCategory.order('lft')) do |category, level| %>
      <tr class="<%= cycle("odd", "even") %> project <%= category.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
      <td class="name"><span><%= link_to category.name, edit_operation_category_path(category) %></span></td>
      <td class="code"><span><%= category.code %></span></td>
      <td class="buttons">
        <%= delete_link operation_category_path(category) %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>