config/routes.rb
# This file is a part of Redmine Finance (redmine_finance) plugin,
# simple accounting plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_finance is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_finance is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_finance.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :accounts
resources :operations do
  collection do
      post :bulk_update
      get :bulk_edit, :context_menu, :auto_complete
      delete :bulk_destroy
  end
end
resources :operation_categories
resources :operation_comments, :only => [:create, :destroy]
resources :operation_invoices, :only => [:create, :destroy]
resources :operation_relations, :only => [:create, :destroy]

resources :operation_imports, :only => [:new, :create]

resources :projects do
  resources :operations

  resources :operation_imports, :only => [:new, :create, :show] do
    member do
      get :settings
      post :settings
      get :mapping
      post :mapping
      get :run
      post :run
    end
  end
end

resources :projects do
  resources :accounts
end

app/helpers/operations_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine Finance (redmine_finance) plugin,
# simple accounting plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_finance is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_finance is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_finance.  If not, see <http://www.gnu.org/licenses/>.

module OperationsHelper
  def operation_categories_for_select(selected = nil)
    @operation_categories ||= OperationCategory.order(:lft).all
  end

  def operation_types_for_select(income)
    s = ''
    s << %Q(<option #{'selected="selected"' if income == true} value="1">#{ l(:label_operation_income) }</option>).html_safe
    s << %Q(<option #{'selected="selected"' if income == false} value="0">#{ l(:label_operation_expense) }</option>).html_safe
    s.html_safe
  end

  def operation_category_tree_options_for_select(operation_categories, options = {})
    s = ''
    OperationCategory.category_tree(operation_categories) do |operation_category, level|
      name_prefix = (level > 0 ? '&nbsp;' * 2 * level + '&#187; ' : '').html_safe
      tag_options = {:value => operation_category.id}
      if operation_category == options[:selected] || (options[:selected].respond_to?(:include?) && options[:selected].include?(operation_category))
        tag_options[:selected] = 'selected'
      else
        tag_options[:selected] = nil
      end
      tag_options.merge!(yield(operation_category)) if block_given?
      s << content_tag('option', name_prefix + h(operation_category.name), tag_options)
    end
    s.html_safe
  end

  def operation_category_url(category_id, options={})
    {:controller => 'operations',
     :action => 'index',
     :set_filter => 1,
     :project_id => @project,
     :fields => [:category_id],
     :values => {:category_id => [category_id]},
     :operators => {:category_id => '='}}.merge(options)
  end

  def operation_category_tree_tag(operation, options={})
    return "" if operation.category.blank?
    operation.category.self_and_ancestors.map do |category|
      link_to category.name, operation_category_url(category.id, options)
    end.join(' &#187; ').html_safe
  end

  def account_tag(account, options={})
    link_to account.name, account_path(account)
  end

  def opeation_tag(operation, options={})
    link_to operation.to_s, account_path(account)
  end

  def operation_list_styles_for_select
    list_styles = [[l(:label_crm_list_list), "list"]]
    list_styles += [[l(:label_calendar), "crm_calendars/crm_calendar"]]
  end

  def operations_list_style
    list_styles = operation_list_styles_for_select.map(&:last)
    if params[:operations_list_style].blank?
      list_style = list_styles.include?(session[:operations_list_style]) ? session[:operations_list_style] : list_styles.first
    else
      list_style = list_styles.include?(params[:operations_list_style]) ? params[:operations_list_style] : list_styles.first
    end
    session[:operations_list_style] = list_style
  end

  def operations_contacts_for_select(project)
    scope = Contact.where({})
    scope = scope.joins(:projects).uniq.where(Contact.visible_condition(User.current))
    scope = scope.joins(:operations => :account)
    scope = scope.where(:accounts => {:project_id => project}) if project
    scope.limit(500).map{|c| [c.name, c.id.to_s]}
  end

  def account_current_balance(previous_balance, operation)
    return previous_balance if RedmineFinance.operations_approval? && !operation.is_approved?
    previous_balance - (operation.is_income? ? operation.amount : -operation.amount)
  end

  def disapproved_operations_url(is_income, options={})
    {:controller => 'operations',
     :action => 'index',
     :set_filter => 1,
     :project_id => @project,
     :fields => [:is_approved, :operation_type],
     :values => {:is_approved => ["0"], :operation_type => [is_income ? "1" : "0"]},
     :operators => {:is_approved => '=', :operation_type => '='}}.merge(options)
  end

  def accounts_for_select(project)
    scope = project ? project.accounts : Account.where({})
    scope.all.map{|a| ["#{a.name} (#{a.currency})", a.id.to_s]}
  end

  def operations_balance_to_currency(income_sum, expense_sum)
    currencies = income_sum.map{|a| a[0]} | expense_sum.map{|a| a[0]}
    currencies.map{|a| price_to_currency(income_sum[a].to_f - expense_sum[a].to_f, a)}.join('<br/>').html_safe
    # operations_balance.map{|c| c[0][1].to_i - c[1][1].to_f}
  end

  def operations_to_csv(operations)
    decimal_separator = l(:general_csv_decimal_separator)
    encoding = l(:general_csv_encoding)
    export = FCSV.generate(:col_sep => l(:general_csv_separator)) do |csv|
      # csv header fields
      headers = [ "#",
                  'Operation date',
                  'Income',
                  'Expense',
                  'Operation type',
                  'Account',
                  'Description',
                  'Contact',
                  'Created',
                  'Updated'
                  ]
      custom_fields = OperationCustomField.all
      custom_fields.each {|f| headers << f.name}
      # Description in the last column
      csv << headers.collect {|c| Redmine::CodesetUtil.from_utf8(c.to_s, encoding) }
      # csv lines
      operations.each do |operation|
        fields = [operation.id,
                  format_time(operation.operation_date),
                  operation.is_income? ? operation.amount : "",
                  operation.is_income? ? "" :  operation.amount,
                  operation.category ? operation.category.name : "",
                  operation.account.name,
                  operation.description,
                  operation.contact,
                  format_time(operation.created_at),
                  format_time(operation.updated_at)
                  ]
        custom_fields.each {|f| fields << RedmineContacts::CSVUtils.csv_custom_value(operation.custom_value_for(f)) }
        csv << fields.collect {|c| Redmine::CodesetUtil.from_utf8(c.to_s, encoding) }
      end
    end
    export
  end

  def _project_operations_path(project, *args)
    if project
      project_operations_path(project, *args)
    else
      operations_path(*args)
    end
  end
  def importer_link
    project_operation_imports_path(:project_id => @project)
  end

  def importer_show_link(importer, project)
    project_operation_import_path(:id => importer, :project_id => project)
  end

  def importer_settings_link(importer, project)
    settings_project_operation_import_path(:id => importer, :project => project)
  end

  def importer_run_link(importer, project)
    run_project_operation_import_path(:id => importer, :project_id => project, :format => 'js')
  end

  def importer_link_to_object(operation)
    link_to operation.description, edit_operation_path(operation)
  end
end

app/views/operations/_custom_field_form.html.erb
<p><%= form.check_box :is_filter %></p>
<% if (@custom_field.respond_to?(:format) && @custom_field.format.searchable_supported) || !@custom_field.respond_to?(:format) %>
<p><%= form.check_box :searchable %></p>
<% end %>

app/views/operations/_form.html.erb
<%= error_messages_for 'operation' %>

<div class="box tabular attributes">

<div class="splitcontentleft">
  <p class="type"><%= f.select :income, operation_types_for_select(@operation.is_income?), :label => l(:label_operation_type), :required => true %></p>
  <p class="category"><%= f.select :category_id, operation_category_tree_options_for_select(operation_categories_for_select, :selected => @operation.category), :label => l(:label_operation_category), :required => true %></p>
  <p class="account"><%= f.select :account_id, accounts_for_select(@project), :label => l(:label_account), :required => true %></p>
  <p class="contact">
    <%= label_tag :operation_contact_id,  l(:label_contact)%>
    <%= select_contact_tag('operation[contact_id]', @operation.contact, :is_select => Contact.visible.by_project(ContactsSetting.cross_project_contacts? ? nil : @project).count < 50, :include_blank => true, :add_contact => true, :display_field => @operation.contact.blank?, :is_company => RedmineFinance.settings[:finance_filter_companies]) %>
  </p>
  <% if RedmineFinance.operations_approval? && User.current.allowed_to?(:approve_operations, @project) %>
  <p><%= f.check_box :is_approved, :label => l(:label_finance_is_approved) %></p>
  <% end %>
</div>

<div class="splitcontentright">
  <p><%= f.text_field :operation_date, :size => 12, :required => true, :value => @operation.operation_date.to_date, :label => l(:label_operation_date) %><%= text_field_tag "operation_time", @operation.operation_time, :size => 5 %><%= calendar_for('operation_operation_date') %> </p>
  <p>
    <%= f.text_field :amount, :label => l(:label_operation_amount), :size => 10, :required => true %>
  </p>
  <p class="object-select"><%= f.select :assigned_to_id, (@project.assignable_users.collect {|m| [m.name, m.id]}), :include_blank => true, :label => l(:field_assigned_to) %></p>
</div>

<div style="clear:both;"> </div>
<% custom_field_values = @operation.custom_field_values %>
<div class="splitcontent">
  <div class="splitcontentleft">
  <% i = 0 %>
  <% split_on = (custom_field_values.size / 2.0).ceil - 1 %>
  <% custom_field_values.each do |value| %>
    <p><%= custom_field_tag_with_label :operation, value, :required => value.custom_field.is_required? %></p>
  <% if i == split_on -%>
  </div><div class="splitcontentright">
  <% end -%>
  <% i += 1 -%>
  <% end -%>
  </div>
</div>
<%= call_hook(:edit_operations_form_details_bottom, { :operation => @operation, :form => f }) %>

<p><%= f.text_area :description, :cols => 60, :rows => 5, :class => 'wiki-edit' %><%= wikitoolbar_for 'operation_description' %></p>

</div>
<fieldset><legend><%= l(:label_attachment_plural) %></legend>
<p><%= render :partial => 'attachments/form', :locals => {:container => @operation} %></p>
</fieldset>
<br>

app/views/operations/_invoices.html.erb
<div class="contextual">
<% if User.current.allowed_to?(:manage_operation_invoices, @project) %>
  <%= toggle_link l(:button_add), 'new-operation-invoice-form', {:focus => 'relation_object_invoice_id'} %>
<% end %>
</div>

<p><strong><%=l(:label_invoice_plural)%></strong></p>

<% for invoice in @invoices %>
<p><%= link_to "##{invoice.number} - #{format_date(invoice.invoice_date)}", invoice_path(invoice), :class => 'icon icon-invoice' -%>
        <%= link_to image_tag('page_white_acrobat_context.png', :plugin => "redmine_contacts_invoices"), invoice_path(invoice, :format => 'pdf') %>
  <span class="amount"><strong><%=  invoice.amount_to_s %></strong></span>
  <%= " - #{invoice.subject}" unless invoice.subject.blank? %>
  <% if invoice.contact %>
    <span class="contact">(<%= invoice.contact.name %>)</span>
  <% end %>

    <%= link_to image_tag('link_break.png'), {:controller => 'operation_invoices',
                                          :action => 'destroy',
                                          :id => invoice.id,
                                          :object_id => invoice.id,
                                          :operation_id => @operation},
                                :remote => true,
                                :method => :delete,
                                :data => {:confirm => l(:text_are_you_sure)},
                                :title => l(:label_relation_delete) if User.current.allowed_to?(:manage_operation_invoices, @project) %>
  </p>
<% end %>

<%= form_for @operation_object, {
                 :as => :operation_object, :remote => true,
                 :url => {:controller => 'operation_invoices', :action => 'create', :operation_id => @operation},
                 :method => :post,
                 :html => {:id => 'new-operation-invoice-form', :style => 'display: none;'}
               } do |f| %>
<%= render :partial => 'operation_invoices/form', :locals => {:f => f}%>
<% end %>

app/views/operations/_list.html.erb
<%= form_tag({}, :data => {:cm_url => context_menu_operations_path}) do -%>
<%= hidden_field_tag 'back_url', url_for(params), :id => nil %>
<%= hidden_field_tag 'project_id', @project.id if @project %>
<div class="autoscroll">
<table class="list operations issues contacts">
  <thead>
    <tr>
      <th class="checkbox hide-when-print">
        <%= link_to image_tag('toggle_check.png'), {},
                              :onclick => 'toggleIssuesSelection(this); return false;',
                              :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
      </th>
      <th>#</th>
      <% @query.inline_columns.each do |column| %>
        <%= content_tag('th', column.caption) %>
      <% end %>
    </tr>
  </thead>
  <% previous_group = false %>
  <tbody>
  <% @operations.each do |operation| -%>
  <% if @query.grouped? && (group = @query.group_by_column.value(operation)) != previous_group %>
    <% reset_cycle %>
    <tr class="group open">
      <td colspan="<%= @query.inline_columns.size + 2 %>">
        <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
        <%= group.blank? ? l(:label_none) : column_content(@query.group_by_column, operation) %> <span class="count"><%= @operation_count_by_group[group] %></span>
        <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                             "toggleAllRowGroups(this)", :class => 'toggle-all') %>
      </td>
    </tr>
    <% previous_group = group %>
  <% end %>
  <tr id="operation-<%= operation.id %>" class="hascontextmenu operation <%= cycle('odd', 'even') %> <%= 'not-approved' if RedmineFinance.operations_approval? && !operation.is_approved? %> <%= 'planned-operation' if operation.operation_date > Time.now  %>">
    <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", operation.id, false, :id => nil) %></td>
    <td class="id"><%= link_to operation.id, operation_path(operation) %></td>
    <%= raw @query.inline_columns.map {|column| "<td class=\"#{column.css_classes}\">#{column_content(column, operation)}</td>"}.join %>
  </tr>
  <% @query.block_columns.each do |column|
       if (text = column_content(column, operation)) && text.present? -%>
  <tr class="<%= current_cycle %>">
    <td colspan="<%= @query.inline_columns.size + 1 %>" class="<%= column.css_classes %>"><%= text %></td>
  </tr>
  <% end -%>
  <% end -%>
  <% end -%>
      <tr class="total">
        <th colspan="3" class="money"><%= l(:label_finance_total) %>:</th><th class="money sum"><%= prices_collection_by_currency(@operations_debit).join('<br>').html_safe %></th><th class="money sum"><%= prices_collection_by_currency(@operations_credit).join('<br>').html_safe %></th><th colspan="<%= @query.inline_columns.size - 4  %>" class="money"><%= l(:label_account_balance) %>:</th><th class="money"><%= operations_balance_to_currency(@operations_debit, @operations_credit) %></th>
      </tr>
  </tbody>
</table>
</div>
<% end -%>

app/views/operations/_relations.html.erb
<div class="contextual">
<% if User.current.allowed_to?(:manage_operation_relations, @project) %>
  <%= toggle_link l(:button_add), 'new-relation-form', {:focus => 'relation_operation_destination_id'} %>
<% end %>
</div>

<p><strong><%=l(:label_related_operations)%></strong></p>

<% @relations.each do |relation| %>
  <p id="relation-<%= relation.id %>" class="icon icon-operation"><%= link_to "#{relation.other_operation(@operation).category.name} ##{relation.other_operation(@operation).id}: #{relation.other_operation(@operation).amount_with_sign} (#{relation.other_operation(@operation).account.name})", relation.other_operation(@operation) %>
    <span class="contact"><%= relation.other_operation(@operation).contact.name if relation.other_operation(@operation).contact %></span>
    <%= link_to image_tag('link_break.png'),
                              {:controller => 'operation_relations', :action => 'destroy', :id => relation},
                              :remote => true,
                              :method => :delete,
                              :data => {:confirm => l(:text_are_you_sure)},
                              :title => l(:label_relation_delete) if User.current.allowed_to?(:manage_operation_relations, @project) %>
  </p>
<% end %>

<%= form_for @relation, {
                 :as => :relation, :remote => true,
                 :url => {:controller => 'operation_relations', :action => 'create', :operation_id => @operation},
                 :method => :post,
                 :html => {:id => 'new-relation-form', :style => 'display: none;'}
               } do |f| %>
<%= render :partial => 'operation_relations/form', :locals => {:f => f}%>
<% end %>

app/views/operations/context_menu.html.erb
<ul>
	<% if @operation %>
		<li><%= context_menu_link l(:button_edit), {:controller => 'operations', :action => 'edit', :id => @operation},
		        :class => 'icon-edit', :disabled => !@can[:edit] %></li>
    <li><%= context_menu_link l(:button_duplicate), {:controller => 'operations', :action => 'new', :project_id => @project, :copy_from => @operation},
          :class => 'icon-duplicate', :disabled => !@can[:edit] %></li>

    <% if RedmineFinance.operations_approval? && User.current.allowed_to?(:approve_operations, @project) %>
  	<li><%= context_menu_link @operation.is_approved? ? l(:label_finance_disapprove) : l(:label_finance_approve), {:controller => 'operations', :action => 'update', :id => @operation, :project_id => @project, :back_url => @back, :operation => {:is_approved => !@operation.is_approved?}}, :method => :put,
	        :class => 'icon icon-checked', :disabled => !@can[:approve] %></li>
    <% end %>
  <% elsif RedmineFinance.operations_approval? && User.current.allowed_to?(:approve_operations, @project, :global => true) %>
    <li class="folder">
      <a href="#" class="submenu"><%= l(:label_finance_approve) %></a>
      <ul>
          <li><%= context_menu_link l(:label_finance_approve), bulk_update_operations_path(:ids => @operations.collect(&:id), :operation => {:is_approved => true}, :back_url => @back), :method => :post, :disabled => !@can[:approve] %></li>
          <li><%= context_menu_link l(:label_finance_disapprove), bulk_update_operations_path(:ids => @operations.collect(&:id), :operation => {:is_approved => false}, :back_url => @back), :method => :post, :disabled => !@can[:approve] %></li>
      </ul>
    </li>
  <% end %>
   	<li><%= context_menu_link l(:button_delete), {:controller => 'operations', :action => 'bulk_destroy', :ids => @operations.collect(&:id), :project_id => @project, :back_url => @back},
                            :method => :delete, :confirm => l(:text_are_you_sure), :class => 'icon-del', :disabled => !@can[:delete] %></li>
    <% if @operation.blank? && Redmine::VERSION.to_s >= '3.3'%>
      <li>
        <%= context_menu_link l(:button_filter), _project_operations_path(@project, :set_filter => 1, :ids => @operations.map(&:id).join(',')),
         :class => 'icon-list' %>
      </li>
  <% end %>

</ul>

app/views/operations/edit.html.erb
<h2><%= l(:label_operation_edit) %></h2>

<%= labelled_form_for :operation, @operation, :url => {:action => 'update', :id => @operation.id}, :html => { :multipart => true, :method => :put, :id => 'operation_form'} do |f|  %>
  <%= render :partial => 'form', :locals => {:f => f}  %>
  <%= submit_tag l(:button_save) -%>
<% end -%>

<% content_for :header_tags do %>
  <%= select2_assets %>
  <%= javascript_include_tag :finance, :plugin => 'redmine_finance'  %>
  <%= stylesheet_link_tag :finance, :plugin => 'redmine_finance' %>
<% end %>

app/views/operations/index.html.erb
<div class="contextual">
  <% if !@query.new_record? && @query.editable_by?(User.current) %>
  <%= link_to l(:button_contacts_edit_query), edit_crm_query_path(@query, :object_type => "operation"), :class => 'icon icon-edit' %>
  <%= link_to l(:button_contacts_delete_query), crm_query_path(@query, :object_type => "operation"), :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %>
  <% end %>
  <%= link_to_if_authorized l(:label_operation_new), {:controller => "operations", :action => "new", :project_id => @project}, :class => 'icon icon-add' %>
  <%= link_to_if_authorized l(:label_crm_import), { :controller => 'operation_imports', :action => :new, :project_id => @project }, :class => 'icon icon-import', :id => 'import_from_csv' %>
</div>

<% html_title(@query.new_record? ? l(:label_operation_plural) : @query.name) %>

<h2><%= @query.new_record? ? l(:label_operation_plural) : h(@query.name)  %></h2>


<%= form_tag({ :controller => 'operations', :action => 'index', :project_id => @project }, :method => :get, :id => 'query_form') do %>
<%= hidden_field_tag 'set_filter', '1' %>
<%= hidden_field_tag 'object_type', 'operation' %>
<div id="query_form_content" class="hide-when-print">
  <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
    <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
    <div style="<%= @query.new_record? ? "" : "display: none;" %>">
      <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
    </div>
  </fieldset>
  <fieldset class="collapsible collapsed">
    <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
    <div style="display: none;">
      <table>
        <tr style="<%= 'display: none;' if operations_list_style != 'list' %>">
          <td><%= l(:field_column_names) %></td>
          <td><%= render_query_columns_selection(@query) %></td>
        </tr>
        <% if operations_list_style == 'list' %>
        <tr>
          <td><label for='group_by'><%= l(:field_group_by) %></label></td>
          <td><%= select_tag('group_by',
                             options_for_select(
                               [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                               @query.group_by)
                     ) %></td>
        </tr>
        <% end %>
        <%= call_hook(:view_operations_index_query_options, :operations => @operations, :query => @query) %>
        <tr>
          <td><label for='operations_list_style'><%= l(:label_crm_list_partial_style) %></label></td>
          <td><%= select_tag('operations_list_style', options_for_select(operation_list_styles_for_select, operations_list_style)) %></td>
        </tr>
      </table>
    </div>
  </fieldset>
</div>
<%= render :partial => "crm_calendars/buttons" if operations_list_style == 'crm_calendars/crm_calendar' %>

<p class="buttons hide-when-print">
  <%= link_to_function l(:button_apply), 'submit_query_form("query_form")', :class => 'icon icon-checked' %>
  <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
  <% if @query.new_record? && User.current.allowed_to?(:save_operations_queries, @project, :global => true) %>
      <%= link_to_function l(:button_save),
                           "$('#query_form').attr('action', '#{ @project ? new_project_crm_query_path(@project) : new_crm_query_path }'); submit_query_form('query_form')",
                           :class => 'icon icon-save' %>

  <% end %>
</p>
<% end %>

<%= error_messages_for 'query' %>
<% if @query.valid? %>
  <div id="contact_list" class="operation_list">
  <% if @operations.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render :partial => operations_list_style %>
    <span class="pagination"><%= pagination_links_full @operations_pages, @operations_count %></span>
  <% end %>
  </div>
  <% other_formats_links do |f| %>
      <%= f.link_to 'CSV', :url => params %>
  <% end %>
<% end %>

<%= javascript_tag "$('.operation_list tr.operation.planned-operation:last').addClass('last');" %>
<% if Redmine::VERSION.to_s >= '3.4' || RedmineContacts.unstable_branch? %>
  <%= context_menu %>
<% else %>
  <%= context_menu url_for( {:controller => "operations", :action => "context_menu"} )%>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'accounts/stat' %>
   <%= render_sidebar_crm_queries('operation') %>
<% end %>

<% content_for :header_tags do %>
  <%= select2_assets %>
  <%= stylesheet_link_tag :finance, :plugin => 'redmine_finance' %>
  <%= stylesheet_link_tag :contacts, :plugin => 'redmine_contacts' %>
  <%= javascript_include_tag :finance, :plugin => 'redmine_finance'  %>
  <meta name = "format-detection" content = "telephone=no">
<% end %>

app/views/operations/new.html.erb
<h2><%= l(:label_operation_new) %></h2>

<%= labelled_form_for :operation, @operation, :url => {:action => 'create', :project_id => @project}, :html => { :multipart => true, :id => 'operation_form'} do |f|  %>
  <%= render :partial => 'form', :locals => {:f => f}  %>
  <%= submit_tag l(:button_save) -%>
<% end -%>


<% content_for :header_tags do %>
  <%= select2_assets %>
  <%= stylesheet_link_tag :finance, :plugin => 'redmine_finance' %>
<% end %>